# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 24 Sep 2012 04:43:20 +0000
*               @ALL          1
*               @user         8
