-- Script was generated by Devart dbForge Studio Express for MySQL, Version 5.0.97.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/12/2012 2:19:24 PM
-- Server version: 5.5.21-log
-- Client version: 4.1

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Definition for table city
--
DROP TABLE IF EXISTS city;
CREATE TABLE city (
  id VARCHAR(45) NOT NULL,
  name VARCHAR(45) NOT NULL,
  `index` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  enable TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE INDEX name (name)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table acc
--
DROP TABLE IF EXISTS acc;
CREATE TABLE acc (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(255) DEFAULT NULL,
  avatar TINYTEXT DEFAULT NULL,
  gender ENUM('MALE','FEMALE','OTHER') DEFAULT NULL,
  dob DATE DEFAULT NULL COMMENT 'day of birth',
  address TINYTEXT DEFAULT NULL,
  city_id VARCHAR(45) DEFAULT NULL,
  created_time TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  last_modified_time TIMESTAMP DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  status ENUM('NORMAL','LOCKED','NOT ACTIVATED YET') NOT NULL DEFAULT 'NOT ACTIVATED YET',
  sources ENUM('VAT_GIA','GOOGLE','FACEBOOK') NOT NULL,
  is_email_verified TINYINT(1) NOT NULL DEFAULT 0,
  is_phone_verified TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE INDEX email (email),
  UNIQUE INDEX phone (phone),
  CONSTRAINT FK_acc__city_id FOREIGN KEY (city_id)
    REFERENCES city(id) ON DELETE RESTRICT ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table acc_auth
--
DROP TABLE IF EXISTS acc_auth;
CREATE TABLE acc_auth (
  id INT(11) UNSIGNED NOT NULL,
  `password` VARCHAR(40) DEFAULT NULL COMMENT 'use sha1 to store hash value',
  password_salt VARCHAR(32) DEFAULT NULL COMMENT 'salt to use HMAC on password',
  secret_question VARCHAR(255) DEFAULT NULL,
  secret_answer VARCHAR(40) DEFAULT NULL COMMENT 'hashed by SHA-1',
  PRIMARY KEY (id),
  CONSTRAINT FK_acc_auth__acc_id FOREIGN KEY (id)
    REFERENCES acc(id) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;